contents/urls.py
from django.conf.urls import patterns, url

from contents import views

urlpatterns = patterns('',
    
    url(r'^$', views.index, name='index'),
    url(r'^$', views.contact, name='contact'),
                       
)

myproject/urls.py
# -*- coding: utf-8 -*-
from django.http import HttpResponsePermanentRedirect
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic.base import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from contents import views
from contents.sitemap import *


sitemaps = {
    'index': MainSitemap,
    'project': ProjectSitemap,
    'service': ServiceSitemap,
    'other': OtherSitemap,
}

handler404 = views.tpl404

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^services/$', views.services, name='services'),
    (r'^service_details/4/$', lambda request: HttpResponsePermanentRedirect('/service_details/3d-mapping-shou/')),
    (r'^service_details/7/$', lambda request: HttpResponsePermanentRedirect('/service_details/interaktivnye-sistemy/')),
    (r'^service_details/6/$', lambda request: HttpResponsePermanentRedirect('/service_details/izgotovlenie-videorolikov/')),
    url(r'^service_details/(?P<service_alias>\S+)/$', views.service_details, name='service_details'),
    url(r'^projects/$', views.projects, name='projects'),
    url(r'^sitemap/$', views.sitemap),
    url(r'^order/$', views.order),
    url(r'^callback/$', views.callback),
    url(r'^project_details/(?P<project_id>\d+)/$', views.project_details, name='project_details'),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^yandex_72fb362f4e1186ce\.txt$', TemplateView.as_view(template_name='yandex_72fb362f4e1186ce.txt', content_type='text/plain')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
                       
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

#if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contents/models.py
# -*- coding: utf-8 -*-

from django.db import models
from sorl.thumbnail import ImageField, get_thumbnail
from _mysql import NULL
# from django.contrib.sites.models import Site


ORIGIN = "orig"
SPECIAL = "spec"
SITE_PART_CHOICES = (
    (ORIGIN, u'Обыкновенный'),
    (SPECIAL, u'Специальный'),
)


# Create your models here.

class Project(models.Model):
    description = models.TextField(u'Полное описание')
    date = models.DateField(u'Дата проекта')
    title = models.CharField(u'Название', max_length=100)
    short_description = models.TextField(u'Краткое описание')
    cover_image = ImageField(u'Обложка', upload_to='projects/cover', help_text=u'Размер 281x281 пикселей.')
    html_title = models.CharField(u'Атрибут "Title"', max_length=100)
    html_alt = models.CharField(u'Атрибут "Alt"', max_length=100)
    page_description = models.TextField(u'Мета тег "description"')
    page_keywords = models.TextField(u'Мета тег "keywords"')

    site_part = models.CharField(u'Тип проекта', max_length=4, choices=SITE_PART_CHOICES, default=ORIGIN)

    class Meta:
        ordering = ['-date']
        verbose_name = u'Проект'
        verbose_name_plural = u'Проекты'

    def __unicode__(self):
        return self.title

class Image(models.Model):
    project = models.ForeignKey(Project)
    image = ImageField(u'Фотография', upload_to='projects/images', help_text=u'Размер 940*529 пикселей.')
    html_title = models.CharField(u'Атрибут "Title"', max_length=100)
    html_alt = models.CharField(u'Атрибут "Alt"', max_length=100)
    ordering = models.PositiveIntegerField(u'Порядок вывода', default=0, db_index=True)

    class Meta:
        ordering = ('ordering',)
        verbose_name = u'Фотография'
        verbose_name_plural = u'Фотографии'

    def __unicode__(self):
        return self.image.path

class ProjectVideo(models.Model):
    project = models.ForeignKey(Project)
    link = models.URLField(u'Адрес Vimeo')
    video_image = ImageField(u'Обложка для видео', upload_to='projects/video/images', help_text=u'Размер 940*529 пикселей.')
    vimeo_number = models.CharField(u'Номер Vimeo', max_length=50)
    image_alt = models.CharField(u'Атрибут "Alt"', max_length=100)
    image_title = models.CharField(u'"Title"', max_length=100)

    class Meta:
        verbose_name = u'Видео'
        verbose_name_plural = u'Все видео'

    def __unicode__(self):
        return self.link

class Service(models.Model):
    title = models.CharField(u'Название', max_length=100)
    short_description = models.TextField (u'Описание')
    ordering = models.PositiveIntegerField(u'Порядок вывода', default=0, db_index=True)
    image = ImageField(u'Обложка для услуги', upload_to='services/images', help_text=u'Размер 940*529 пикселей.')
    image_alt = models.CharField(u'Атрибут "Alt"', max_length=100)
    image_title = models.CharField(u'Атрибут "Title"', max_length=100)
    main_page = models.BooleanField(u'Показывать на главной странице', default=False, db_index=True)
    veryshort_description = models.TextField (u'Краткое описание', blank=True)
    page_description = models.TextField(u'Мета тег "description"')
    page_keywords = models.TextField(u'Мета тег "keywords"')
    page_h1 = models.CharField(u'Заголовок H1' , blank=True, max_length=600)
    page_h1.default = ''
    
    page_alias = models.CharField(u'Алиас', blank=True, max_length=255)
    page_alias.default = ''
    
    page_title = models.CharField(u'Тайтл', blank=True, max_length=255)
    page_title.default = ''

    site_part = models.CharField(u'Тип услуги', max_length=4, choices=SITE_PART_CHOICES, default=ORIGIN)
    special_service = models.BooleanField(u'Спец услуга', default=False, db_index=True)

    class Meta:
        ordering = ['ordering']
        verbose_name = u'Услуга'
        verbose_name_plural = u'Услуги'

    def __unicode__(self):
        return self.title

class ServiceVideo(models.Model):
    service = models.ForeignKey(Service)
    link = models.URLField(u'Адрес Vimeo')
    video_image = ImageField(u'Обложка для видео', upload_to='services/video/images', help_text=u'Размер 940*529 пикселей.')
    vimeo_number = models.CharField(u'Номер Vimeo', max_length=50)
    image_alt = models.CharField(u'Атрибут "Alt"', max_length=100)
    image_title = models.CharField(u'"Title"', max_length=100)

    class Meta:
        verbose_name = u'Видео'
        verbose_name_plural = u'Все видео'

    def __unicode__(self):
        return self.link

class SubService(models.Model):
    service = models.ForeignKey(Service)
    title = models.CharField(u'Наименование', max_length=100)
    descritpion = models.TextField(u'Описание')
    image = ImageField(u'Обложка', upload_to='subservices/images', help_text=u'Размер 281x281 пикселей.')
    image_alt = models.CharField(u'Атрибут "Alt"', max_length=100)
    image_title = models.CharField(u'Атрибут "Title"', max_length=100)

    class Meta:
        verbose_name = u'Подпункт услуги'
        verbose_name_plural = u'Подпункты услуги'

    def __unicode__(self):
        return self.title

class SubImage(models.Model):
    service = models.ForeignKey(SubService)
    image = ImageField(u'Фотография', upload_to='subservices/images', help_text=u'Размер 281x281 пикселей.')
    is_cover_image = models.BooleanField(u'Обложка?', default=False, db_index=True)
    html_title = models.CharField(u'Атрибут "Title"', max_length=100)
    html_alt = models.CharField(u'Атрибут "Alt"', max_length=100)

    class Meta:
        verbose_name = u'Фотография'
        verbose_name_plural = u'Фотографии'

    def __unicode__(self):
        return self.image.path

    def cover_image(self):
        try:
            return self.image_set.get(is_cover_image=True)
        except SubImage.DoesNotExist:
            return None

    def not_cover_image(self):
        try:
            return self.image_set.filter(is_cover_image=False)
        except SubImage.DoesNotExist:
            return None

class Contact(models.Model):
    title = models.CharField(u'Наименование', max_length=100)
    adress = models.CharField(u'Адрес', max_length=100)
    phone = models.CharField(u'Телефон', max_length=100)
    fax = models.CharField(u'Факс', max_length=100)
    email = models.CharField(u'Email', max_length=100)
    gl_country = models.CharField(u'Страна', max_length=50)
    gl_city = models.CharField(u'Город', max_length=50)
    gl_street = models.CharField(u'Улица', max_length=50)
    gl_bld = models.CharField(u'Дом', max_length=5)
    gl_korpus = models.CharField(u'Корпус', max_length=5, blank=True)

    class Meta:
        verbose_name = u'Контакты'
        verbose_name_plural = u'Контакты'

    def __unicode__(self):
        return self.title

class CompanyInfo(models.Model):
    title = models.CharField(u'Наименование', max_length=100)
    description = models.TextField (u'Описание')
    ordering = models.PositiveIntegerField(u'Порядок вывода', default=0, db_index=True)

    site_part = models.CharField(u'Тип информации', max_length=4, choices=SITE_PART_CHOICES, default=ORIGIN)

    class Meta:
        ordering = ['ordering']
        verbose_name = u'Информация о компании'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.title

class MainTeaser(models.Model):
    title = models.CharField(u'Наименование', max_length=100)
    image = ImageField(u'Фото', upload_to='mainteaser/images', help_text=u'Размер 1920x550 пикселей.')
    ordering = models.PositiveIntegerField(u'Порядок вывода', default=0, db_index=True)
    html_title = models.CharField(u'Атрибут "Title"', max_length=100)
    html_alt = models.CharField(u'Атрибут "Alt"', max_length=100)

    class Meta:
        ordering = ['ordering']
        verbose_name = u'Тизер на главной странице'
        verbose_name_plural = u'Тизеры на главной странице'

    def __unicode__(self):
        return self.title

class SubTeaser(models.Model):
    title = models.CharField(u'Наименование', max_length=100)
    image = ImageField(u'Фото', upload_to='subteaser/images', help_text=u'Размер 1920x550 пикселей.')
    html_title = models.CharField(u'Атрибут "Title"', max_length=100)
    html_alt = models.CharField(u'Атрибут "Alt"', max_length=100)

    class Meta:
        verbose_name = u'Тизер на дополнительных страницах'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.title

class ServiceImage(models.Model):
    service = models.ForeignKey(Service)
    image = ImageField(u'Фотография', upload_to='services/images', help_text=u'Размер 940*529 пикселей.')
    html_title = models.CharField(u'"Title"', max_length=100)
    html_alt = models.CharField(u'Атрибут "Alt"', max_length=100)
    ordering = models.PositiveIntegerField(u'Порядок вывода', default=0, db_index=True)

    class Meta:
        ordering = ('ordering',)
        verbose_name = u'Фотография'
        verbose_name_plural = u'Фотографии'

    def __unicode__(self):
        return self.image.path

class HtmlAttributes(models.Model):
    MAIN = "mn"
    SERVICES = "sr"
    PROJECTS = "pr"
    CONTACT = "ct"
    PAGE_TYPE_CHOICES = (
        (MAIN, u'Главная'),
        (SERVICES, u'Сервисы'),
        (PROJECTS, u'Проекты'),
        (CONTACT, u'Контакты'),
    )
    page_type = models.CharField(max_length=2, choices=PAGE_TYPE_CHOICES, default=MAIN)
    page_title = models.CharField(u'Атрибут "Title" страницы', max_length=100)
    page_description = models.TextField(u'Мета тег "description"')
    page_keywords = models.TextField(u'Мета тег "keywords"')

    class Meta:
        verbose_name = u'HTML атрибут для основных страниц'
        verbose_name_plural = u'HTML атрибуты для основных страниц'

    def __unicode__(self):
        return self.page_title

templates/company_old.html
{% extends 'base.html' %}
{% block page_title %}О компании{% endblock %}

<!--==============================Content=================================-->
{% block content %}

<div class="content">
  <div class="container_12 prv">
    <div class="grid_4 fright">
      <h3>terms of use</h3>
      <p>Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. </p>
      <p>Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus.</p>
      Quisque nulla. Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque. Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sollicitudin velit sed leo. Ut pharetra augue nec augue. Nam elit magna, hendrerit sit amet, tincidunt ac, viverra sed, nulla. 
    </div>
    <div class="grid_8 pr">
      <h3>privacy policy</h3>
      <p>Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus.</p>
      <p>Quisque nulla. Vestibulum libero nisl, porta vel, scelerisque eget, malesuada at, neque. Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sollicitudin velit sed leo. Ut pharetra augue nec augue. Nam elit magna, hendrerit sit amet, tincidunt ac, viverra sed, nulla. Donec porta diam eu massa. Quisque diam lorem, interdum vitae, dapibus ac, scelerisque vitae, pede. Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctor pulvinar. Proin ullamcorper urna et felis.</p>
      <p>Vestibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula. Aliquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibulum sed ante. Donec sagittis euismod purus.</p>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas.</p>
      <p>Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. </p>
      Email: <a href="#">privacy@demolink.org </a>
    </div>
  </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block page_title %}{{ html_attributes.page_title }}{% endblock %}
{% block page_keywords %}{{ html_attributes.page_keywords }}{% endblock %}
{% block page_description %}{{ html_attributes.page_description }}{% endblock %}
{% block contact_act %}current{% endblock %}

<!--==============================Content=================================-->
{% block content %}
<div class="content">
		<div class="container_12">
		<div class="grid_12">
		<span class = "breadcrumbs">
    		<a href="/">Главная</a> > {{ html_attributes.page_title }}
    	</span>
		</div>
		</div>
  <div class="container_12">
    <div class="grid_6">
      <h3>Найти нас</h3>
      <div class="map">
        <figure class=" ">
          <script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=N10NOSHo185LJu82eAf_roGpxeNf69WJ&width=600&height=450"></script>
        </figure>
      </div>
    </div>
    <div class="grid_6">
      <h3>Связаться с нами</h3>
        <address>
          <dl>
            <dt>
            {{ contacts.adress }}
            </dt>
            <dd><span>Телефон: </span>{{ contacts.phone }}</dd>
            <dd><span>FAX: </span>{{ contacts.fax }}</dd>
            <dd><span>E-mail: </span><a href="{{ contacts.email }}">{{ contacts.email }}</a></dd>
          </dl>
        </address>
    </div>
  </div>
</div>
{% endblock %}

templates/project_details.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load thumbnail %}
{% block page_title %}{{ project.title }}{% endblock %}
{% block page_keywords %}{{ project.page_keywords }}{% endblock %}
{% block page_description %}{{ project.page_description }}{% endblock %}

<!--==============================Content=================================-->
{% block content %}
<div class="content">
  <div class="container_12">
  <span class = "breadcrumbs">
    		<a href="/">Главная</a> > <a href="/services">{{ html_attributes.page_title }}</a> > {{ project.title }}
    	</span>
    <div class="grid_12 center">
      <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
      <div id="blueimp-gallery-carousel" class="blueimp-gallery blueimp-gallery-controls blueimp-gallery-carousel">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
      </div>
      <div id="links">
        {% for video in project.projectvideo_set.all %}
        {% thumbnail video.video_image "940x529" crop="center" as cover %}
        <a
        href="{{ video }}"
        data-vimeo="{{ video.vimeo_number }}"
        type="text/html"
        data-poster="{{ cover.url }}"
        rel = "nofollow"
        >
        </a>
        {% endthumbnail %}
        {% endfor %}

        {% for image in project.image_set.all %}
        {% thumbnail image "940x529" crop="center" as im %}
        <a href="{{ im.url }}" title=""></a>
        {% endthumbnail %}
        {% endfor %}
      </div>
      <!-- end the Gallery Blueimp -->
      <div class="project_details">
        <h1 class="center details_h">{{ project.title }}</h1>
        <p>{{ project.description }}</p>
      </div>
    </div>
  </div>
</div>

<script src="{{ STATIC_URL }}js/blueimp/blueimp-gallery.min.js"></script>
<script src="{{ STATIC_URL }}js/blueimplocal.js"></script>

{% endblock %}

templates/projects.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block page_title %}{{ html_attributes.page_title }}{% endblock %}
{% block page_keywords %}{{ html_attributes.page_keywords }}{% endblock %}
{% block page_description %}{{ html_attributes.page_description }}{% endblock %}
{% block project_act %}current{% endblock %}

<!--==============================Content=================================-->
{% block content %}
<div class="content">
  <div class="container_12 center">
    <div class="grid_12">
		<span class = "breadcrumbs">
    		<a href="/">Главная</a> > {{ html_attributes.page_title }}
    	</span>
      <h1 class="projects_h1">наши проекты</h1>
    </div>
    <div class="clear"></div>
    <div class="serv">
      {% for project in projects %}
      <div class="grid_4">
        <a href="/project_details/{{ project.id }}/" class="gal">
          {% thumbnail project.cover_image "281x281" crop="center" as im %}
          <img alt="{{ project.html_alt }}" title="{{ project.html_title }}" src="{{ im.url }}">
          {% endthumbnail %}
        </a>
        <p class="col2 upp">
          <strong>
            <a href="/project_details/{{ project.id }}/">{{ project.title }}</a>
          </strong>
        </p>
        {{ project.short_description }}
        <br>
        <a href="/project_details/{{ project.id }}/" class="btn">читать далее</a>
      </div>
        {% if forloop.counter|divisibleby:"3" %}
        <div class="clear"></div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/service_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block page_title %}
	{% if service.page_title %}
		{{ service.page_title }}
	{% else %}
		{{ service.title }}
	{% endif %}
{% endblock %}
{% block page_keywords %}{{ service.page_keywords }}{% endblock %}
{% block page_description %}{{ service.page_description }}{% endblock %}
   
<!--==============================Content=================================-->
{% block content %}
<div class="content">
  <div class="container_12">
    <span class = "breadcrumbs">
    		<a href="/">Главная</a> > <a href="/services">{{ html_attributes.page_title }}</a> > {{ service.title }}
    	</span>
    <div class="grid_12 center">
		
      <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
      <div id="blueimp-gallery-carousel" class="blueimp-gallery blueimp-gallery-controls blueimp-gallery-carousel">
          <div class="slides"></div>
          <h3 class="title"></h3>
          <a class="prev">‹</a>
          <a class="next">›</a>
          <a class="play-pause"></a>
          <ol class="indicator"></ol>
      </div>

      <div id="links">
          {% for video in service.servicevideo_set.all %}
          {% thumbnail video.video_image "940x529" crop="center" as cover %}
            <a
              href="{{ video.link }}"
              data-vimeo="{{ video.vimeo_number }}"
              type="text/html"
              data-poster="{{ cover.url }}" 
              rel = "nofollow"
              >
            </a>
          {% endthumbnail %}
          {% endfor %}

        {% for image in service.serviceimage_set.all %}
        {% thumbnail image "940x529" crop="center" as im %}
        <a href="{{ im.url }}" title="" ></a>
        {% endthumbnail %}
        {% endfor %}
      </div>
      <!-- end the Gallery Blueimp -->

	    {% if service.page_h1 %}
		    <h1 class="video_name details_serv">{{ service.page_h1 | safe}}</h1>
	    {% else %}
            <h1 class="video_name details_serv">{{ service.title | safe}}</h1>
	    {% endif %}
      
      <p class="project_details">{{ service.short_description | safe}}</p>

      <div class="serv">

        {% for subservice in service.subservice_set.all %}
        <div class="grid_12">
          <div class="grid_4">
            {% thumbnail subservice.image "281x281" crop="center" as cover %}
            <a class="gal nohover"><img src="{{ cover.url }}" alt=""></a>
            {% endthumbnail %}
          </div>
          <p class="upp white"><strong>{{ subservice.title }}</strong></p>
          <p class="project_details">{{ subservice.descritpion | safe }}</p>
        </div>
        {% endfor %}
		<a href="{% static 'files/Brif_na_razrabptku_kreativnoi_koncepcii_PT.doc' %}" class="brif_button">Cкачать бриф</a>
		
		
      </div>  
    </div>
  </div>
		<div class="order_form_wraper">
			<div class="order_form_title">
			Сделайте заявку прямо сейчас
			</div>
			<div class="container_12">
			<form id="order_form" action="/order">
				<textarea placeholder="Ваша заявка или письмо&#8230;" name="message" cols="50" rows="8"></textarea>
				<div class="order_form_r">
				<input class="order_input" type="text" id="order_user_name" name="user_name" placeholder="Ваше имя">
				<input class="order_input" type="text" name="email" id="order_user_email" placeholder="Ваш е-mail">
				<input class="order_input tel" type="text" id="order_user_tel" name="tel" placeholder="Ваш телефон">
				{% csrf_token %}
				</div>
			
			</form>
			<a href="#" id="submit_order" class="submit_order">Отправить заявку</a>
			</div>
		</div>
</div>

<script src="{{ STATIC_URL }}js/blueimp/blueimp-gallery.min.js"></script>
<script src="{{ STATIC_URL }}js/blueimplocal.js"></script>
<script type="text/javascript">
$(function() {
    $('#submit_order').click(function(){
        var msg   = $('#order_form').serialize();
		var pattern = /^.+@.+[.].{2,}$/i;
        if($('#order_user_name').val()==''){
            alert('Пожалуйста, представьтесь');
            return false;
        };
        if($('#order_user_tel').val()==''){
            alert('Пожалуйста, укажите номер телефона');
            return false;
        };
		if($('#order_user_email').val()==''){
            alert('Пожалуйста, укажите свой email');
            return false;
        }else{
			if(!pattern.test($('#order_user_email').val())){
				alert('Пожалуйста, укажите правильный email');
				return false;
			}
		};
        $.ajax({
          type: 'POST',
          url: '/order/',
          data: msg,
          success: function(data) {
            $('#order_form').html('<span class="order_result">'+data+'</span>');
          },
          error:  function(xhr, str){
                alert('Возникла ошибка: ' + xhr.responseCode);
            }
        });
        return false;
    });
});
</script>
{% endblock %}

templates/sitemap.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block page_title %}Карта сайта{% endblock %}
{% block content %}
<div class="content">
<div class="container_12">
		<span class = "breadcrumbs">
    		<a href="/">Главная</a> > Карта сайта
    	</span>
<div class="clear"></div>
<div class="grid_12" style="margin-top:100px">
<ul>
	<li>
		<a href="/">главная</a>
	</li>
	<ul>
		<li>
			<a href="/services/">{{service_attributes.page_title}}</a>
		</li>
		<li>
			<a href="/projects/">{{project_attributes.page_title}}</a>
		</li>
		<li>
			<a href="/contact/">{{contact_attributes.page_title}}</a>
		</li>
	</ul>
</ul>
</div>
</div>
</div>
{% endblock %}